/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Override;
import java.lang.String;
import java.net.http.HttpResponse;
import java.util.Optional;
import to.unified.unified_java_sdk.models.shared.Error;
import to.unified.unified_java_sdk.models.shared.Order;
import to.unified.unified_java_sdk.utils.AsyncResponse;
import to.unified.unified_java_sdk.utils.Blob;
import to.unified.unified_java_sdk.utils.Utils;


public class CreateOrderResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * An unknown error occurred interacting with the API.
     */
    private Error error;

    /**
     * The order was created successfully.
     */
    private Order order;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    @JsonCreator
    public CreateOrderResponse(
            @Nonnull String contentType,
            @Nullable Error error,
            @Nullable Order order,
            int statusCode,
            @Nonnull HttpResponse<Blob> rawResponse) {
        this.contentType = Optional.ofNullable(contentType)
            .orElseThrow(() -> new IllegalArgumentException("contentType cannot be null"));
        this.error = error;
        this.order = order;
        this.statusCode = statusCode;
        this.rawResponse = Optional.ofNullable(rawResponse)
            .orElseThrow(() -> new IllegalArgumentException("rawResponse cannot be null"));
    }
    
    public CreateOrderResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<Blob> rawResponse) {
        this(contentType, null, null,
            statusCode, rawResponse);
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * An unknown error occurred interacting with the API.
     */
    public Optional<Error> error() {
        return Optional.ofNullable(this.error);
    }

    /**
     * The order was created successfully.
     */
    public Optional<Order> order() {
        return Optional.ofNullable(this.order);
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return this.statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<Blob> rawResponse() {
        return this.rawResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public CreateOrderResponse withContentType(@Nonnull String contentType) {
        this.contentType = Utils.checkNotNull(contentType, "contentType");
        return this;
    }


    /**
     * An unknown error occurred interacting with the API.
     */
    public CreateOrderResponse withError(@Nullable Error error) {
        this.error = error;
        return this;
    }


    /**
     * The order was created successfully.
     */
    public CreateOrderResponse withOrder(@Nullable Order order) {
        this.order = order;
        return this;
    }


    /**
     * HTTP response status code for this operation
     */
    public CreateOrderResponse withStatusCode(int statusCode) {
        this.statusCode = statusCode;
        return this;
    }


    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public CreateOrderResponse withRawResponse(@Nonnull HttpResponse<Blob> rawResponse) {
        this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateOrderResponse other = (CreateOrderResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.error, other.error) &&
            Utils.enhancedDeepEquals(this.order, other.order) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, error, order,
            statusCode, rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateOrderResponse.class,
                "contentType", contentType,
                "error", error,
                "order", order,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Error error;

        private Order order;

        private int statusCode;

        private HttpResponse<Blob> rawResponse;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(@Nonnull String contentType) {
            this.contentType = Utils.checkNotNull(contentType, "contentType");
            return this;
        }

        /**
         * An unknown error occurred interacting with the API.
         */
        public Builder error(@Nullable Error error) {
            this.error = error;
            return this;
        }

        /**
         * The order was created successfully.
         */
        public Builder order(@Nullable Order order) {
            this.order = order;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(@Nonnull HttpResponse<Blob> rawResponse) {
            this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
            return this;
        }

        public CreateOrderResponse build() {
            return new CreateOrderResponse(
                contentType, error, order,
                statusCode, rawResponse);
        }

    }
}
