/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk;

import static to.unified.unified_java_sdk.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import to.unified.unified_java_sdk.models.operations.ListIngredientsRequest;
import to.unified.unified_java_sdk.models.operations.async.ListIngredientsRequestBuilder;
import to.unified.unified_java_sdk.models.operations.async.ListIngredientsResponse;
import to.unified.unified_java_sdk.operations.ListIngredients;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Options;

/**
 * The ingredients endpoints.
 */
public class AsyncIngredients {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Ingredients syncSDK;

    AsyncIngredients(Ingredients syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Ingredients sync() {
        return syncSDK;
    }


    /**
     * Get a list of ingredients.
     * 
     * <p>Get a list of ingredients, if authenticated this will include stock levels and product codes
     * otherwise it will only include public information.
     * 
     * @return The async call builder
     */
    public ListIngredientsRequestBuilder listIngredients() {
        return new ListIngredientsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a list of ingredients.
     * 
     * <p>Get a list of ingredients, if authenticated this will include stock levels and product codes
     * otherwise it will only include public information.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<ListIngredientsResponse>} - The async response
     */
    public CompletableFuture<ListIngredientsResponse> listIngredients(@Nonnull ListIngredientsRequest request) {
        return listIngredients(request, null);
    }

    /**
     * Get a list of ingredients.
     * 
     * <p>Get a list of ingredients, if authenticated this will include stock levels and product codes
     * otherwise it will only include public information.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<ListIngredientsResponse>} - The async response
     */
    public CompletableFuture<ListIngredientsResponse> listIngredients(@Nonnull ListIngredientsRequest request, @Nullable Options options) {
        AsyncRequestOperation<ListIngredientsRequest, ListIngredientsResponse> operation
              = new ListIngredients.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
