/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk;

import static to.unified.unified_java_sdk.operations.Operations.AsyncRequestOperation;
import static to.unified.unified_java_sdk.operations.Operations.AsyncRequestlessOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import to.unified.unified_java_sdk.models.operations.GetFoodRequest;
import to.unified.unified_java_sdk.models.operations.async.GetFoodRequestBuilder;
import to.unified.unified_java_sdk.models.operations.async.GetFoodResponse;
import to.unified.unified_java_sdk.models.operations.async.ListFoodsRequestBuilder;
import to.unified.unified_java_sdk.models.operations.async.ListFoodsResponse;
import to.unified.unified_java_sdk.operations.GetFood;
import to.unified.unified_java_sdk.operations.ListFoods;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Options;

/**
 * The food endpoints.
 */
public class AsyncFood {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Food syncSDK;

    AsyncFood(Food syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Food sync() {
        return syncSDK;
    }


    /**
     * Get a food item.
     * 
     * <p>Get a food item by name.
     * 
     * @return The async call builder
     */
    public GetFoodRequestBuilder getFood() {
        return new GetFoodRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a food item.
     * 
     * <p>Get a food item by name.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<GetFoodResponse>} - The async response
     */
    public CompletableFuture<GetFoodResponse> getFood(@Nonnull GetFoodRequest request) {
        return getFood(request, null);
    }

    /**
     * Get a food item.
     * 
     * <p>Get a food item by name.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<GetFoodResponse>} - The async response
     */
    public CompletableFuture<GetFoodResponse> getFood(@Nonnull GetFoodRequest request, @Nullable Options options) {
        AsyncRequestOperation<GetFoodRequest, GetFoodResponse> operation
              = new GetFood.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get a list of food items.
     * 
     * <p>Get a list of food items.
     * 
     * @return The async call builder
     */
    public ListFoodsRequestBuilder listFoods() {
        return new ListFoodsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a list of food items.
     * 
     * <p>Get a list of food items.
     * 
     * @return {@code CompletableFuture<ListFoodsResponse>} - The async response
     */
    public CompletableFuture<ListFoodsResponse> listFoodsDirect() {
        return listFoods(null);
    }

    /**
     * Get a list of food items.
     * 
     * <p>Get a list of food items.
     * 
     * @param options additional options
     * @return {@code CompletableFuture<ListFoodsResponse>} - The async response
     */
    public CompletableFuture<ListFoodsResponse> listFoods(@Nullable Options options) {
        AsyncRequestlessOperation<ListFoodsResponse> operation
            = new ListFoods.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest()
            .thenCompose(operation::handleResponse);
    }

}
