/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk;

import to.unified.unified_java_sdk.utils.Headers;

/**
 * The Speakeasy Bar: A bar that serves drinks.
 * 
 * <p>A secret underground bar that serves drinks to those in the know.
 * 
 * <p><a href="https://docs.speakeasy.bar">The Speakeasy Bar Documentation.</a>
 */
public class AsyncUnifiedTo {
    private static final Headers _headers = Headers.EMPTY;
    /**
     * The authentication endpoints.
     */
    private final AsyncAuthentication authentication;
    /**
     * The drinks endpoints.
     */
    private final AsyncDrinks drinks;
    /**
     * The food endpoints.
     */
    private final AsyncFood food;
    /**
     * The ingredients endpoints.
     */
    private final AsyncIngredients ingredients;
    /**
     * The orders endpoints.
     */
    private final AsyncOrders orders;

    private final AsyncConfig config;
    /**
     * The authentication endpoints.
     */
    public AsyncAuthentication authentication() {
        return authentication;
    }
    /**
     * The drinks endpoints.
     */
    public AsyncDrinks drinks() {
        return drinks;
    }
    /**
     * The food endpoints.
     */
    public AsyncFood food() {
        return food;
    }
    /**
     * The ingredients endpoints.
     */
    public AsyncIngredients ingredients() {
        return ingredients;
    }
    /**
     * The orders endpoints.
     */
    public AsyncOrders orders() {
        return orders;
    }

    public AsyncConfig config() {
        return config;
    }

    private final SDKConfiguration sdkConfiguration;
    private final UnifiedTo syncSDK;

    AsyncUnifiedTo(UnifiedTo syncSDK, SDKConfiguration sdkConfiguration) {
        this.syncSDK = syncSDK;
        this.sdkConfiguration = sdkConfiguration;
        this.authentication = new AsyncAuthentication(syncSDK.authentication(), sdkConfiguration);
        this.drinks = new AsyncDrinks(syncSDK.drinks(), sdkConfiguration);
        this.food = new AsyncFood(syncSDK.food(), sdkConfiguration);
        this.ingredients = new AsyncIngredients(syncSDK.ingredients(), sdkConfiguration);
        this.orders = new AsyncOrders(syncSDK.orders(), sdkConfiguration);
        this.config = new AsyncConfig(syncSDK.config(), sdkConfiguration);
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public UnifiedTo sync() {
        return syncSDK;
    }
}
