/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk;

import static to.unified.unified_java_sdk.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import to.unified.unified_java_sdk.models.operations.GetDrinkRequest;
import to.unified.unified_java_sdk.models.operations.ListDrinksRequest;
import to.unified.unified_java_sdk.models.operations.async.GetDrinkRequestBuilder;
import to.unified.unified_java_sdk.models.operations.async.GetDrinkResponse;
import to.unified.unified_java_sdk.models.operations.async.ListDrinksRequestBuilder;
import to.unified.unified_java_sdk.models.operations.async.ListDrinksResponse;
import to.unified.unified_java_sdk.operations.GetDrink;
import to.unified.unified_java_sdk.operations.ListDrinks;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Options;

/**
 * The drinks endpoints.
 */
public class AsyncDrinks {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Drinks syncSDK;

    AsyncDrinks(Drinks syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Drinks sync() {
        return syncSDK;
    }


    /**
     * Get a drink.
     * 
     * <p>Get a drink by name, if authenticated this will include stock levels and product codes otherwise it
     * will only include public information.
     * 
     * @return The async call builder
     */
    public GetDrinkRequestBuilder getDrink() {
        return new GetDrinkRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a drink.
     * 
     * <p>Get a drink by name, if authenticated this will include stock levels and product codes otherwise it
     * will only include public information.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<GetDrinkResponse>} - The async response
     */
    public CompletableFuture<GetDrinkResponse> getDrink(@Nonnull GetDrinkRequest request) {
        return getDrink(request, null);
    }

    /**
     * Get a drink.
     * 
     * <p>Get a drink by name, if authenticated this will include stock levels and product codes otherwise it
     * will only include public information.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<GetDrinkResponse>} - The async response
     */
    public CompletableFuture<GetDrinkResponse> getDrink(@Nonnull GetDrinkRequest request, @Nullable Options options) {
        AsyncRequestOperation<GetDrinkRequest, GetDrinkResponse> operation
              = new GetDrink.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get a list of drinks.
     * 
     * <p>Get a list of drinks, if authenticated this will include stock levels and product codes otherwise it
     * will only include public information.
     * 
     * <p>If set, this operation will use Security#clientCredentials from the global security.
     * 
     * @return The async call builder
     */
    public ListDrinksRequestBuilder listDrinks() {
        return new ListDrinksRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a list of drinks.
     * 
     * <p>Get a list of drinks, if authenticated this will include stock levels and product codes otherwise it
     * will only include public information.
     * 
     * <p>If set, this operation will use Security#clientCredentials from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<ListDrinksResponse>} - The async response
     */
    public CompletableFuture<ListDrinksResponse> listDrinks(@Nonnull ListDrinksRequest request) {
        return listDrinks(request, null);
    }

    /**
     * Get a list of drinks.
     * 
     * <p>Get a list of drinks, if authenticated this will include stock levels and product codes otherwise it
     * will only include public information.
     * 
     * <p>If set, this operation will use Security#clientCredentials from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<ListDrinksResponse>} - The async response
     */
    public CompletableFuture<ListDrinksResponse> listDrinks(@Nonnull ListDrinksRequest request, @Nullable Options options) {
        AsyncRequestOperation<ListDrinksRequest, ListDrinksResponse> operation
              = new ListDrinks.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
