/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk;

import static to.unified.unified_java_sdk.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import to.unified.unified_java_sdk.models.operations.RequestBody;
import to.unified.unified_java_sdk.models.operations.async.SubscribeToWebhooksRequestBuilder;
import to.unified.unified_java_sdk.models.operations.async.SubscribeToWebhooksResponse;
import to.unified.unified_java_sdk.operations.SubscribeToWebhooks;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Options;


public class AsyncConfig {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Config syncSDK;

    AsyncConfig(Config syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Config sync() {
        return syncSDK;
    }


    /**
     * Subscribe to webhooks.
     * 
     * <p>Subscribe to webhooks.
     * 
     * @return The async call builder
     */
    public SubscribeToWebhooksRequestBuilder subscribeToWebhooks() {
        return new SubscribeToWebhooksRequestBuilder(sdkConfiguration);
    }

    /**
     * Subscribe to webhooks.
     * 
     * <p>Subscribe to webhooks.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<SubscribeToWebhooksResponse>} - The async response
     */
    public CompletableFuture<SubscribeToWebhooksResponse> subscribeToWebhooks(@Nonnull List<RequestBody> request) {
        return subscribeToWebhooks(request, null);
    }

    /**
     * Subscribe to webhooks.
     * 
     * <p>Subscribe to webhooks.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<SubscribeToWebhooksResponse>} - The async response
     */
    public CompletableFuture<SubscribeToWebhooksResponse> subscribeToWebhooks(@Nonnull List<RequestBody> request, @Nullable Options options) {
        AsyncRequestOperation<List<RequestBody>, SubscribeToWebhooksResponse> operation
              = new SubscribeToWebhooks.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
