/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk;

import static to.unified.unified_java_sdk.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import to.unified.unified_java_sdk.models.operations.CreateOrderRequest;
import to.unified.unified_java_sdk.models.operations.async.CreateOrderRequestBuilder;
import to.unified.unified_java_sdk.models.operations.async.CreateOrderResponse;
import to.unified.unified_java_sdk.operations.CreateOrder;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Options;

/**
 * The orders endpoints.
 */
public class AsyncOrders {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Orders syncSDK;

    AsyncOrders(Orders syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Orders sync() {
        return syncSDK;
    }


    /**
     * Create an order.
     * 
     * <p>Create an order for a drink.
     * 
     * @return The async call builder
     */
    public CreateOrderRequestBuilder createOrder() {
        return new CreateOrderRequestBuilder(sdkConfiguration);
    }

    /**
     * Create an order.
     * 
     * <p>Create an order for a drink.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<CreateOrderResponse>} - The async response
     */
    public CompletableFuture<CreateOrderResponse> createOrder(@Nonnull CreateOrderRequest request) {
        return createOrder(request, null);
    }

    /**
     * Create an order.
     * 
     * <p>Create an order for a drink.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<CreateOrderResponse>} - The async response
     */
    public CompletableFuture<CreateOrderResponse> createOrder(@Nonnull CreateOrderRequest request, @Nullable Options options) {
        AsyncRequestOperation<CreateOrderRequest, CreateOrderResponse> operation
              = new CreateOrder.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
