/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk;

import static to.unified.unified_java_sdk.operations.Operations.AsyncRequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import to.unified.unified_java_sdk.models.operations.AuthenticateRequestBody;
import to.unified.unified_java_sdk.models.operations.async.AuthenticateRequestBuilder;
import to.unified.unified_java_sdk.models.operations.async.AuthenticateResponse;
import to.unified.unified_java_sdk.operations.Authenticate;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Options;

/**
 * The authentication endpoints.
 */
public class AsyncAuthentication {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Authentication syncSDK;

    AsyncAuthentication(Authentication syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Authentication sync() {
        return syncSDK;
    }


    /**
     * Authenticate with the API by providing a username and password.
     * 
     * @return The async call builder
     */
    public AuthenticateRequestBuilder authenticate() {
        return new AuthenticateRequestBuilder(sdkConfiguration);
    }

    /**
     * Authenticate with the API by providing a username and password.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<AuthenticateResponse>} - The async response
     */
    public CompletableFuture<AuthenticateResponse> authenticate(@Nonnull AuthenticateRequestBody request) {
        return authenticate(request, null);
    }

    /**
     * Authenticate with the API by providing a username and password.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<AuthenticateResponse>} - The async response
     */
    public CompletableFuture<AuthenticateResponse> authenticate(@Nonnull AuthenticateRequestBody request, @Nullable Options options) {
        AsyncRequestOperation<AuthenticateRequestBody, AuthenticateResponse> operation
              = new Authenticate.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
