/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import to.unified.unified_java_sdk.models.operations.AuthenticateRequestBody;
import to.unified.unified_java_sdk.models.operations.AuthenticateRequestBuilder;
import to.unified.unified_java_sdk.models.operations.AuthenticateResponse;
import to.unified.unified_java_sdk.operations.Authenticate;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Options;

/**
 * The authentication endpoints.
 */
public class Authentication {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncAuthentication asyncSDK;

    Authentication(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncAuthentication(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncAuthentication async() {
        return asyncSDK;
    }

    /**
     * Authenticate with the API by providing a username and password.
     * 
     * @return The call builder
     */
    public AuthenticateRequestBuilder authenticate() {
        return new AuthenticateRequestBuilder(sdkConfiguration);
    }

    /**
     * Authenticate with the API by providing a username and password.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public AuthenticateResponse authenticate(@Nonnull AuthenticateRequestBody request) {
        return authenticate(request, null);
    }

    /**
     * Authenticate with the API by providing a username and password.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public AuthenticateResponse authenticate(@Nonnull AuthenticateRequestBody request, @Nullable Options options) {
        RequestOperation<AuthenticateRequestBody, AuthenticateResponse> operation
              = new Authenticate.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
