/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.List;
import to.unified.unified_java_sdk.models.operations.RequestBody;
import to.unified.unified_java_sdk.models.operations.SubscribeToWebhooksRequestBuilder;
import to.unified.unified_java_sdk.models.operations.SubscribeToWebhooksResponse;
import to.unified.unified_java_sdk.operations.SubscribeToWebhooks;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Options;


public class Config {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncConfig asyncSDK;

    Config(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncConfig(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncConfig async() {
        return asyncSDK;
    }

    /**
     * Subscribe to webhooks.
     * 
     * <p>Subscribe to webhooks.
     * 
     * @return The call builder
     */
    public SubscribeToWebhooksRequestBuilder subscribeToWebhooks() {
        return new SubscribeToWebhooksRequestBuilder(sdkConfiguration);
    }

    /**
     * Subscribe to webhooks.
     * 
     * <p>Subscribe to webhooks.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribeToWebhooksResponse subscribeToWebhooks(@Nonnull List<RequestBody> request) {
        return subscribeToWebhooks(request, null);
    }

    /**
     * Subscribe to webhooks.
     * 
     * <p>Subscribe to webhooks.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribeToWebhooksResponse subscribeToWebhooks(@Nonnull List<RequestBody> request, @Nullable Options options) {
        RequestOperation<List<RequestBody>, SubscribeToWebhooksResponse> operation
              = new SubscribeToWebhooks.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
