/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import to.unified.unified_java_sdk.models.operations.GetDrinkRequest;
import to.unified.unified_java_sdk.models.operations.GetDrinkRequestBuilder;
import to.unified.unified_java_sdk.models.operations.GetDrinkResponse;
import to.unified.unified_java_sdk.models.operations.ListDrinksRequest;
import to.unified.unified_java_sdk.models.operations.ListDrinksRequestBuilder;
import to.unified.unified_java_sdk.models.operations.ListDrinksResponse;
import to.unified.unified_java_sdk.operations.GetDrink;
import to.unified.unified_java_sdk.operations.ListDrinks;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Options;

/**
 * The drinks endpoints.
 */
public class Drinks {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncDrinks asyncSDK;

    Drinks(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncDrinks(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncDrinks async() {
        return asyncSDK;
    }

    /**
     * Get a drink.
     * 
     * <p>Get a drink by name, if authenticated this will include stock levels and product codes otherwise it
     * will only include public information.
     * 
     * @return The call builder
     */
    public GetDrinkRequestBuilder getDrink() {
        return new GetDrinkRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a drink.
     * 
     * <p>Get a drink by name, if authenticated this will include stock levels and product codes otherwise it
     * will only include public information.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetDrinkResponse getDrink(@Nonnull GetDrinkRequest request) {
        return getDrink(request, null);
    }

    /**
     * Get a drink.
     * 
     * <p>Get a drink by name, if authenticated this will include stock levels and product codes otherwise it
     * will only include public information.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetDrinkResponse getDrink(@Nonnull GetDrinkRequest request, @Nullable Options options) {
        RequestOperation<GetDrinkRequest, GetDrinkResponse> operation
              = new GetDrink.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get a list of drinks.
     * 
     * <p>Get a list of drinks, if authenticated this will include stock levels and product codes otherwise it
     * will only include public information.
     * 
     * <p>If set, this operation will use Security#clientCredentials from the global security.
     * 
     * @return The call builder
     */
    public ListDrinksRequestBuilder listDrinks() {
        return new ListDrinksRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a list of drinks.
     * 
     * <p>Get a list of drinks, if authenticated this will include stock levels and product codes otherwise it
     * will only include public information.
     * 
     * <p>If set, this operation will use Security#clientCredentials from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListDrinksResponse listDrinks(@Nonnull ListDrinksRequest request) {
        return listDrinks(request, null);
    }

    /**
     * Get a list of drinks.
     * 
     * <p>Get a list of drinks, if authenticated this will include stock levels and product codes otherwise it
     * will only include public information.
     * 
     * <p>If set, this operation will use Security#clientCredentials from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListDrinksResponse listDrinks(@Nonnull ListDrinksRequest request, @Nullable Options options) {
        RequestOperation<ListDrinksRequest, ListDrinksResponse> operation
              = new ListDrinks.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
