/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;
import static to.unified.unified_java_sdk.operations.Operations.RequestlessOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import to.unified.unified_java_sdk.models.operations.GetFoodRequest;
import to.unified.unified_java_sdk.models.operations.GetFoodRequestBuilder;
import to.unified.unified_java_sdk.models.operations.GetFoodResponse;
import to.unified.unified_java_sdk.models.operations.ListFoodsRequestBuilder;
import to.unified.unified_java_sdk.models.operations.ListFoodsResponse;
import to.unified.unified_java_sdk.operations.GetFood;
import to.unified.unified_java_sdk.operations.ListFoods;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Options;

/**
 * The food endpoints.
 */
public class Food {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncFood asyncSDK;

    Food(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncFood(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncFood async() {
        return asyncSDK;
    }

    /**
     * Get a food item.
     * 
     * <p>Get a food item by name.
     * 
     * @return The call builder
     */
    public GetFoodRequestBuilder getFood() {
        return new GetFoodRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a food item.
     * 
     * <p>Get a food item by name.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetFoodResponse getFood(@Nonnull GetFoodRequest request) {
        return getFood(request, null);
    }

    /**
     * Get a food item.
     * 
     * <p>Get a food item by name.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetFoodResponse getFood(@Nonnull GetFoodRequest request, @Nullable Options options) {
        RequestOperation<GetFoodRequest, GetFoodResponse> operation
              = new GetFood.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get a list of food items.
     * 
     * <p>Get a list of food items.
     * 
     * @return The call builder
     */
    public ListFoodsRequestBuilder listFoods() {
        return new ListFoodsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a list of food items.
     * 
     * <p>Get a list of food items.
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListFoodsResponse listFoodsDirect() {
        return listFoods(null);
    }

    /**
     * Get a list of food items.
     * 
     * <p>Get a list of food items.
     * 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListFoodsResponse listFoods(@Nullable Options options) {
        RequestlessOperation<ListFoodsResponse> operation
            = new ListFoods.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest());
    }

}
