/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import to.unified.unified_java_sdk.models.operations.ListIngredientsRequest;
import to.unified.unified_java_sdk.models.operations.ListIngredientsRequestBuilder;
import to.unified.unified_java_sdk.models.operations.ListIngredientsResponse;
import to.unified.unified_java_sdk.operations.ListIngredients;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Options;

/**
 * The ingredients endpoints.
 */
public class Ingredients {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncIngredients asyncSDK;

    Ingredients(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncIngredients(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncIngredients async() {
        return asyncSDK;
    }

    /**
     * Get a list of ingredients.
     * 
     * <p>Get a list of ingredients, if authenticated this will include stock levels and product codes
     * otherwise it will only include public information.
     * 
     * @return The call builder
     */
    public ListIngredientsRequestBuilder listIngredients() {
        return new ListIngredientsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a list of ingredients.
     * 
     * <p>Get a list of ingredients, if authenticated this will include stock levels and product codes
     * otherwise it will only include public information.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListIngredientsResponse listIngredients(@Nonnull ListIngredientsRequest request) {
        return listIngredients(request, null);
    }

    /**
     * Get a list of ingredients.
     * 
     * <p>Get a list of ingredients, if authenticated this will include stock levels and product codes
     * otherwise it will only include public information.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListIngredientsResponse listIngredients(@Nonnull ListIngredientsRequest request, @Nullable Options options) {
        RequestOperation<ListIngredientsRequest, ListIngredientsResponse> operation
              = new ListIngredients.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
