/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import to.unified.unified_java_sdk.models.operations.CreateOrderRequest;
import to.unified.unified_java_sdk.models.operations.CreateOrderRequestBuilder;
import to.unified.unified_java_sdk.models.operations.CreateOrderResponse;
import to.unified.unified_java_sdk.operations.CreateOrder;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Options;

/**
 * The orders endpoints.
 */
public class Orders {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncOrders asyncSDK;

    Orders(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncOrders(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncOrders async() {
        return asyncSDK;
    }

    /**
     * Create an order.
     * 
     * <p>Create an order for a drink.
     * 
     * @return The call builder
     */
    public CreateOrderRequestBuilder createOrder() {
        return new CreateOrderRequestBuilder(sdkConfiguration);
    }

    /**
     * Create an order.
     * 
     * <p>Create an order for a drink.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateOrderResponse createOrder(@Nonnull CreateOrderRequest request) {
        return createOrder(request, null);
    }

    /**
     * Create an order.
     * 
     * <p>Create an order for a drink.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateOrderResponse createOrder(@Nonnull CreateOrderRequest request, @Nullable Options options) {
        RequestOperation<CreateOrderRequest, CreateOrderResponse> operation
              = new CreateOrder.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
