/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package to.unified.unified_java_sdk;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.HashMap;
import java.util.Map.Entry;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Consumer;
import to.unified.unified_java_sdk.utils.HTTPClient;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Hook.SdkInitData;
import to.unified.unified_java_sdk.utils.RetryConfig;
import to.unified.unified_java_sdk.utils.SpeakeasyHTTPClient;
import to.unified.unified_java_sdk.utils.Utils;

/**
 * The Speakeasy Bar: A bar that serves drinks.
 * 
 * <p>A secret underground bar that serves drinks to those in the know.
 * 
 * <p><a href="https://docs.speakeasy.bar">The Speakeasy Bar Documentation.</a>
 */
public class UnifiedTo {
    private static final Headers _headers = Headers.EMPTY;

    /**
     * AvailableServers contains identifiers for the servers available to the SDK.
     */
    public enum AvailableServers {
        /**
         * PROD
         * 
         * <p>The production server.
         */
        PROD("prod"),
        /**
         * STAGING
         * 
         * <p>The staging server.
         */
        STAGING("staging"),
        /**
         * CUSTOMER
         * 
         * <p>A per-organization and per-environment API.
         */
        CUSTOMER("customer");

        private final String server;

        AvailableServers(String server) {
            this.server = server;
        }

        public String server() {
           return server;
        }
    }

    /**
     * SERVERS contains the list of server urls available to the SDK.
     */
    @SuppressWarnings("serial")
    public static final Map<AvailableServers, String> SERVERS = new HashMap<>() { {
        put(AvailableServers.PROD, "https://speakeasy.bar");
        put(AvailableServers.STAGING, "https://staging.speakeasy.bar");
        put(AvailableServers.CUSTOMER, "https://{organization}.{environment}.speakeasy.bar");
    }};

    /**
     * The authentication endpoints.
     */
    private final Authentication authentication;

    /**
     * The drinks endpoints.
     */
    private final Drinks drinks;

    /**
     * The food endpoints.
     */
    private final Food food;

    /**
     * The ingredients endpoints.
     */
    private final Ingredients ingredients;

    /**
     * The orders endpoints.
     */
    private final Orders orders;


    private final Config config;

    /**
     * The authentication endpoints.
     */
    public Authentication authentication() {
        return authentication;
    }

    /**
     * The drinks endpoints.
     */
    public Drinks drinks() {
        return drinks;
    }

    /**
     * The food endpoints.
     */
    public Food food() {
        return food;
    }

    /**
     * The ingredients endpoints.
     */
    public Ingredients ingredients() {
        return ingredients;
    }

    /**
     * The orders endpoints.
     */
    public Orders orders() {
        return orders;
    }


    public Config config() {
        return config;
    }
    private final AsyncUnifiedTo asyncSDK;

    /**
     * The Builder class allows the configuration of a new instance of the SDK.
     */
    public static class Builder {

        private final SDKConfiguration sdkConfiguration = new SDKConfiguration();
        private String serverUrl;
        private String server;
        

        private Builder() {
        }

        /**
         * Allows the default HTTP client to be overridden with a custom implementation.
         *
         * @param client The HTTP client to use for all requests.
         * @return The builder instance.
         */
        public Builder client(HTTPClient client) {
            this.sdkConfiguration.setClient(client);
            return this;
        }
        
        /**
         * Configures the SDK to use the provided security details.
         *
         * @param security The security details to use for all requests. Can be {@code null}.
         * @return The builder instance.
         */
        public Builder security(to.unified.unified_java_sdk.models.shared.Security security) {
            this.sdkConfiguration.setSecuritySource(SecuritySource.of(security));
            return this;
        }

        /**
         * Configures the SDK to use a custom security source.
         *
         * @param securitySource The security source to use for all requests.
         * @return The builder instance.
         */
        public Builder securitySource(SecuritySource securitySource) {
            Utils.checkNotNull(securitySource, "securitySource");
            this.sdkConfiguration.setSecuritySource(securitySource);
            return this;
        }
        
        /**
         * Overrides the default server URL.
         *
         * @param serverUrl The server URL to use for all requests.
         * @return The builder instance.
         */
        public Builder serverURL(String serverUrl) {
            this.serverUrl = serverUrl;
            return this;
        }

        /**
         * Overrides the default server URL with a templated URL populated with the provided parameters.
         *
         * @param serverUrl The server URL to use for all requests.
         * @param params The parameters to use when templating the URL.
         * @return The builder instance.
         */
        public Builder serverURL(String serverUrl, Map<String, String> params) {
            this.serverUrl = Utils.templateUrl(serverUrl, params);
            return this;
        }
        
        /**
         * Overrides the default server by name.
         *
         * @param server The server to use for all requests.
         * @return The builder instance.
         */
        public Builder server(AvailableServers server) {
            this.server = server.server();
            this.serverUrl = SERVERS.get(server);
            return this;
        }
        
        /**
         * Overrides the default configuration for retries
         *
         * @param retryConfig The retry configuration to use for all requests.
         * @return The builder instance.
         */
        public Builder retryConfig(RetryConfig retryConfig) {
            this.sdkConfiguration.setRetryConfig(Optional.of(retryConfig));
            return this;
        }

        /**
         * Enables debug logging for HTTP requests and responses, including JSON body content.
         * <p>
         * Convenience method that calls {@link HTTPClient#enableDebugLogging(boolean)}.
         * {@link SpeakeasyHTTPClient} honors this setting. If you are using a custom HTTP client,
         * it is up to the custom client to honor this setting.
         * </p>
         *
         * @param enabled Whether to enable debug logging.
         * @return The builder instance.
         */
        public Builder enableHTTPDebugLogging(boolean enabled) {
            this.sdkConfiguration.client().enableDebugLogging(enabled);
            return this;
        }

        /**
         * ServerEnvironment
         * 
         * <p>The environment name. Defaults to the production environment.
         */
        public enum ServerEnvironment {
            PROD("prod"),
            STAGING("staging"),
            DEV("dev");

            @JsonValue    
            private final String value;

            ServerEnvironment(String value) {
                this.value = value;
            }

            public String value() {
                return value;
            }

            public static Optional<ServerEnvironment> fromValue(String value) {
                for (ServerEnvironment o: ServerEnvironment.values()) {
                    if (Objects.deepEquals(o.value, value)) {
                        return Optional.of(o);
                    }
                }
                return Optional.empty();
            }
        }
        /**
         * Sets the environment variable for url substitution.
         *
         * @param environment The value to set.
         * @return The builder instance.
         */
        public Builder environment(ServerEnvironment environment) {
            for (Entry<String, Map<String, String>> entry : this.sdkConfiguration.serverVariables().entrySet()) {
                Map<String, String> server = entry.getValue();

                if (!server.containsKey("environment")) {
                    continue;
                }
                server.put("environment", environment.toString());
            }

            return this;
        }
        /**
         * Sets the organization variable for url substitution.
         *
         * @param organization The value to set.
         * @return The builder instance.
         */
        public Builder organization(String organization) {
            for (Entry<String, Map<String, String>> entry : this.sdkConfiguration.serverVariables().entrySet()) {
                Map<String, String> server = entry.getValue();

                if (!server.containsKey("organization")) {
                    continue;
                }
                server.put("organization", organization);
            }

            return this;
        }
        // Visible for testing, may be accessed via reflection in tests
        Builder _hooks(to.unified.unified_java_sdk.utils.Hooks hooks) {
            sdkConfiguration.setHooks(hooks);  
            return this;  
        }
        
        // Visible for testing, may be accessed via reflection in tests
        Builder _hooks(Consumer<? super to.unified.unified_java_sdk.utils.Hooks> consumer) {
            consumer.accept(sdkConfiguration.hooks());
            return this;    
        }

        /**
         * Builds a new instance of the SDK.
         *
         * @return The SDK instance.
         */
        public UnifiedTo build() {
            if (serverUrl == null || serverUrl.isBlank()) {
                serverUrl = SERVERS.get(AvailableServers.PROD);
                server = AvailableServers.PROD.server();
            }
            sdkConfiguration.setServerUrl(serverUrl);
            if (server != null) {
                sdkConfiguration.setServer(server);
            }
            return new UnifiedTo(sdkConfiguration);
        }
    }

    /**
     * Get a new instance of the SDK builder to configure a new instance of the SDK.
     *
     * @return The SDK builder instance.
     */
    public static Builder builder() {
        return new Builder();
    }

    public UnifiedTo(SDKConfiguration sdkConfiguration) {
        sdkConfiguration.initialize();
        this.authentication = new Authentication(sdkConfiguration);
        this.drinks = new Drinks(sdkConfiguration);
        this.food = new Food(sdkConfiguration);
        this.ingredients = new Ingredients(sdkConfiguration);
        this.orders = new Orders(sdkConfiguration);
        this.config = new Config(sdkConfiguration);
        SdkInitData data = sdkConfiguration.hooks().sdkInit(
                new SdkInitData(
                        sdkConfiguration.resolvedServerUrl(), 
                        sdkConfiguration.client()));
        sdkConfiguration.setServerUrl(data.baseUrl());
        sdkConfiguration.setClient(data.client());
        this.asyncSDK = new AsyncUnifiedTo(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncUnifiedTo async() {
        return asyncSDK;
    }

}
