/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk;

import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import java.util.concurrent.TimeUnit;

import java.lang.IllegalStateException;
import java.lang.String;
import java.lang.System;
import java.util.Optional;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.function.Consumer;
import to.unified.unified_java_sdk.utils.BackoffStrategy;
import to.unified.unified_java_sdk.utils.HTTPClient;
import to.unified.unified_java_sdk.utils.RetryConfig;
import to.unified.unified_java_sdk.utils.SpeakeasyHTTPClient;


/**
 * Spring Boot Auto Configuration for Unified-java-sdk SDK
 * This configuration class automatically configures the Unified-java-sdk SDK
 * when Spring Boot detects it on the classpath.
 */
@AutoConfiguration
@ConditionalOnClass(UnifiedTo.class)
@EnableConfigurationProperties(UnifiedJavaSDKAutoConfigProperties.class)
public class UnifiedJavaSDKAutoConfig {

    /**
     * Constructor.
     */
    public UnifiedJavaSDKAutoConfig() {
    }

    /**
     * Creates a RetryConfig bean from properties if retry is enabled.
     * 
     * @param properties the configuration properties
     * @return A configured RetryConfig instance
     */
    @Bean
    @ConditionalOnMissingBean
    @ConditionalOnProperty(prefix = "unifiedjavasdk.retry-config", name = "strategy")
    public RetryConfig retryConfig(UnifiedJavaSDKAutoConfigProperties properties) {
        UnifiedJavaSDKAutoConfigProperties.RetryConfig retryProps = properties.getRetryConfig();
        
        if (RetryConfig.Strategy.BACKOFF.equals(retryProps.getStrategy())) {
            UnifiedJavaSDKAutoConfigProperties.RetryConfig.Backoff backoff = retryProps.getBackoff();
            return RetryConfig.builder()
                .backoff(
                    BackoffStrategy.builder()
                        .initialInterval(backoff.getInitialInterval().toMillis(), TimeUnit.MILLISECONDS)
                        .maxInterval(backoff.getMaxInterval().toMillis(), TimeUnit.MILLISECONDS)
                        .maxElapsedTime(backoff.getMaxElapsedTime().toMillis(), TimeUnit.MILLISECONDS)
                        .baseFactor(backoff.getBaseFactor())
                        .jitterFactor(backoff.getJitterFactor())
                        .retryConnectError(backoff.isRetryConnectError())
                        .retryReadTimeoutError(backoff.isRetryReadTimeoutError())
                        .build()
                )
                .build();
        }
        
        // Default retry config for other strategies
        return RetryConfig.builder().build();
    }
    /**
     * Creates a {@code Consumer<String>} bean for HTTP debug logging if none exists.
     * This logger is used by the SpeakeasyHTTPClient for debug output when debug logging is enabled.
     * By default, it logs to {@code System.out}, but can be customized by providing your own {@code Consumer<String>} bean.
     *
     * @return A {@code Consumer<String>} that logs messages to {@code System.out}
     */
    @Bean
    @ConditionalOnMissingBean
    public Consumer<String> httpLogger() {
        return System.out::println;
    }
    /**
     * Creates an HTTPClient bean if none exists.
     *
     * @param properties the configuration properties
     * @param httpLogger the logger for HTTP debug output
     * @return A configured HTTPClient instance
     */
    @Bean
    @ConditionalOnMissingBean
    public HTTPClient httpClient(UnifiedJavaSDKAutoConfigProperties properties, Consumer<String> httpLogger) {
        UnifiedJavaSDKAutoConfigProperties.HttpClient httpClientProps = properties.getHttpClient();

        // Configure the static logger
        SpeakeasyHTTPClient.setLogger(httpLogger);

        if (httpClientProps != null) {
            // Configure debug logging
            SpeakeasyHTTPClient.setDebugLogging(httpClientProps.isEnableDebugLogging());

            // Configure redacted headers
            if (httpClientProps.getRedactedHeaders() != null && !httpClientProps.getRedactedHeaders().isEmpty()) {
                SpeakeasyHTTPClient.setRedactedHeaders(httpClientProps.getRedactedHeaders());
            }
        }

        return new SpeakeasyHTTPClient();
    }
    /**
     * Creates a SecuritySource bean if none exists and security properties are configured.
     *
     * @param properties the configuration properties
     * @return A configured SecuritySource instance
     */
    @Bean
    @ConditionalOnMissingBean
    @ConditionalOnPropertyPrefix(prefix = "unifiedjavasdk.security")
    public SecuritySource securitySource(UnifiedJavaSDKAutoConfigProperties properties) {UnifiedJavaSDKAutoConfigProperties.Security securityProps = properties.getSecurity();
        to.unified.unified_java_sdk.models.shared.Security.Builder securityBuilder = to.unified.unified_java_sdk.models.shared.Security.builder();
        boolean hasAnySecurityConfiguration = false;
        // Build apiKey security from direct properties (primitive value)
        if (securityProps.getApiKey() != null) {
            securityBuilder.apiKey(securityProps.getApiKey());
            hasAnySecurityConfiguration = true;
        }
        // Build clientCredentials security from direct properties (primitive value)
        if (securityProps.getClientCredentials() != null) {
            securityBuilder.clientCredentials(securityProps.getClientCredentials());
            hasAnySecurityConfiguration = true;
        }
        
        if (!hasAnySecurityConfiguration) {
            throw new IllegalStateException("Security configuration is present but no security options are configured. " +
                "Please configure at least one security option in your application properties.");
        }
        
        return SecuritySource.of(securityBuilder.build());
    }

    /**
     * Creates the SDKConfiguration bean as the single source of truth for all SDK configuration.
     *
     * @param properties the configuration properties
     * @param httpClient the HTTP client bean
     * @param hooks the hooks bean
     * @param asyncHooks the async hooks bean
     * @param securitySource the security source bean (optional)
     * @param retryConfig the retry config bean (optional)
     * @return A configured SDKConfiguration instance
     */
    @Bean
    @ConditionalOnMissingBean
    public SDKConfiguration sdkConfiguration(
            UnifiedJavaSDKAutoConfigProperties properties,
            HTTPClient httpClient,
            to.unified.unified_java_sdk.utils.Hooks hooks,
            to.unified.unified_java_sdk.utils.AsyncHooks asyncHooks,
            SecuritySource securitySource,
            Optional<RetryConfig> retryConfig) {
        
        SDKConfiguration sdkConfiguration = new SDKConfiguration();
        
        sdkConfiguration.setClient(httpClient);
        
        sdkConfiguration.setHooks(hooks);
        sdkConfiguration.setAsyncHooks(asyncHooks);
        sdkConfiguration.setSecuritySource(securitySource);
        
        if (properties.getServerUrl() != null) {
            sdkConfiguration.setServerUrl(properties.getServerUrl());
        }
        if (properties.getServer() != null) {
            sdkConfiguration.setServer(properties.getServer());
        }
        
        sdkConfiguration.setRetryConfig(retryConfig);
        
        return sdkConfiguration;
    }

    /**
     * Creates the main SDK bean using the configured SDKConfiguration.
     *
     * @param sdkConfiguration the configured SDKConfiguration bean
     * @return A configured UnifiedTo instance
     */
    @Bean
    @ConditionalOnMissingBean
    public UnifiedTo unifiedTo(SDKConfiguration sdkConfiguration) {
        return new UnifiedTo(sdkConfiguration);
    }

    /**
     * Creates an AsyncHooks bean if none exists.
     * 
     * @return A configured AsyncHooks instance
     */
    @Bean
    @ConditionalOnMissingBean
    public to.unified.unified_java_sdk.utils.AsyncHooks asyncHooks() {
        return new to.unified.unified_java_sdk.utils.AsyncHooks();
    }

    /**
     * Creates a ScheduledExecutorService for async retry operations if none exists.
     * 
     * @return A configured ScheduledExecutorService instance
     */
    @Bean
    @ConditionalOnMissingBean
    public ScheduledExecutorService retryScheduler() {
        return Executors.newSingleThreadScheduledExecutor();
    }

    /**
     * Creates a Hooks configuration bean if none exists.
     *
     * @return A configured Hooks instance
     */
    @Bean
    @ConditionalOnMissingBean
    public to.unified.unified_java_sdk.utils.Hooks hooks() {
        return new to.unified.unified_java_sdk.utils.Hooks();
    }
    /**
     * Creates a Authentication sub-SDK bean if none exists.
     *
     * @param unifiedTo the main SDK instance
     * @return A configured Authentication instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Authentication authentication(UnifiedTo unifiedTo) {
        return unifiedTo.authentication();
    }
    /**
     * Creates a Drinks sub-SDK bean if none exists.
     *
     * @param unifiedTo the main SDK instance
     * @return A configured Drinks instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Drinks drinks(UnifiedTo unifiedTo) {
        return unifiedTo.drinks();
    }
    /**
     * Creates a Food sub-SDK bean if none exists.
     *
     * @param unifiedTo the main SDK instance
     * @return A configured Food instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Food food(UnifiedTo unifiedTo) {
        return unifiedTo.food();
    }
    /**
     * Creates a Ingredients sub-SDK bean if none exists.
     *
     * @param unifiedTo the main SDK instance
     * @return A configured Ingredients instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Ingredients ingredients(UnifiedTo unifiedTo) {
        return unifiedTo.ingredients();
    }
    /**
     * Creates a Orders sub-SDK bean if none exists.
     *
     * @param unifiedTo the main SDK instance
     * @return A configured Orders instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Orders orders(UnifiedTo unifiedTo) {
        return unifiedTo.orders();
    }
    /**
     * Creates a Config sub-SDK bean if none exists.
     *
     * @param unifiedTo the main SDK instance
     * @return A configured Config instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Config config(UnifiedTo unifiedTo) {
        return unifiedTo.config();
    }

    /**
     * Creates the async SDK bean if none exists.
     *
     * @param unifiedTo the main SDK instance
     * @param sdkConfiguration the configured SDKConfiguration bean
     * @return A configured AsyncUnifiedTo instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncUnifiedTo asyncUnifiedTo(UnifiedTo unifiedTo, SDKConfiguration sdkConfiguration) {
        return new AsyncUnifiedTo(unifiedTo, sdkConfiguration);
    }
    /**
     * Creates an AsyncAuthentication sub-SDK bean if none exists.
     *
     * @param asyncUnifiedTo the async SDK instance
     * @return A configured AsyncAuthentication instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncAuthentication asyncAuthentication(AsyncUnifiedTo asyncUnifiedTo) {
        return asyncUnifiedTo.authentication();
    }
    /**
     * Creates an AsyncDrinks sub-SDK bean if none exists.
     *
     * @param asyncUnifiedTo the async SDK instance
     * @return A configured AsyncDrinks instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncDrinks asyncDrinks(AsyncUnifiedTo asyncUnifiedTo) {
        return asyncUnifiedTo.drinks();
    }
    /**
     * Creates an AsyncFood sub-SDK bean if none exists.
     *
     * @param asyncUnifiedTo the async SDK instance
     * @return A configured AsyncFood instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncFood asyncFood(AsyncUnifiedTo asyncUnifiedTo) {
        return asyncUnifiedTo.food();
    }
    /**
     * Creates an AsyncIngredients sub-SDK bean if none exists.
     *
     * @param asyncUnifiedTo the async SDK instance
     * @return A configured AsyncIngredients instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncIngredients asyncIngredients(AsyncUnifiedTo asyncUnifiedTo) {
        return asyncUnifiedTo.ingredients();
    }
    /**
     * Creates an AsyncOrders sub-SDK bean if none exists.
     *
     * @param asyncUnifiedTo the async SDK instance
     * @return A configured AsyncOrders instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncOrders asyncOrders(AsyncUnifiedTo asyncUnifiedTo) {
        return asyncUnifiedTo.orders();
    }
    /**
     * Creates an AsyncConfig sub-SDK bean if none exists.
     *
     * @param asyncUnifiedTo the async SDK instance
     * @return A configured AsyncConfig instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncConfig asyncConfig(AsyncUnifiedTo asyncUnifiedTo) {
        return asyncUnifiedTo.config();
    }
}