/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.errors;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Deprecated;
import java.lang.Exception;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.lang.Throwable;
import java.net.http.HttpResponse;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import to.unified.unified_java_sdk.utils.Blob;
import to.unified.unified_java_sdk.utils.Utils;

@SuppressWarnings("serial")
public class APIError extends UnifiedToError {

    @Nullable
    private final Data data;

    @Nullable
    private final Throwable deserializationException;

    public APIError(
                int code,
                byte[] body,
                HttpResponse<?> rawResponse,
                @Nullable Data data,
                @Nullable Throwable deserializationException) {
        super("API error occurred", code, body, rawResponse, null);
        this.data = data;
        this.deserializationException = deserializationException;
    }

    /**
    * Parse a response into an instance of APIError. If deserialization of the response body fails,
    * the resulting APIError instance will have a null data() value and a non-null deserializationException().
    */
    public static APIError from(HttpResponse<InputStream> response) {
        try {
            byte[] bytes = Utils.extractByteArrayFromBody(response);
            Data data = Utils.mapper().readValue(bytes, Data.class);
            return new APIError(response.statusCode(), bytes, response, data, null);
        } catch (Exception e) {
            return new APIError(response.statusCode(), null, response, null, e);
        }
    }

    /**
    * Parse a response into an instance of APIError asynchronously. If deserialization of the response body fails,
    * the resulting APIError instance will have a null data() value and a non-null deserializationException().
    */
    public static CompletableFuture<APIError> fromAsync(HttpResponse<Blob> response) {
        return response.body()
                .toByteArray()
                .handle((bytes, err) -> {
                    // if a body read error occurs, we want to transform the exception
                    if (err != null) {
                        throw new AsyncSDKError(
                                "Error reading response body: " + err.getMessage(),
                                response.statusCode(),
                                null,
                                response,
                                err);
                    }

                    try {
                        return new APIError(
                                response.statusCode(),
                                bytes,
                                response,
                                Utils.mapper().readValue(
                                        bytes,
                                        new TypeReference<Data>() {
                                        }),
                                null);
                    } catch (Exception e) {
                        return new APIError(
                                response.statusCode(),
                                bytes,
                                response,
                                null,
                                e);
                    }
                });
    }

    @Deprecated
    public Optional<Map<String, Object>> details() {
        return data().flatMap(Data::details);
    }

    public Optional<Data> data() {
        return Optional.ofNullable(data);
    }

    /**
     * Returns the exception if an error occurs while deserializing the response body.
     */
    public Optional<Throwable> deserializationException() {
        return Optional.ofNullable(deserializationException);
    }
    /**
     * Data
     * 
     * <p>An error occurred interacting with the API.
     */
    public static class Data {

        @JsonInclude(Include.NON_ABSENT)
        @JsonProperty("code")
        private String code;


        @JsonInclude(Include.NON_ABSENT)
        @JsonProperty("details")
        private Map<String, Object> details;


        @JsonInclude(Include.NON_ABSENT)
        @JsonProperty("message")
        private String message;

        @JsonCreator
        public Data(
                @JsonProperty("code") @Nullable String code,
                @JsonProperty("details") @Nullable Map<String, Object> details,
                @JsonProperty("message") @Nullable String message) {
            this.code = code;
            this.details = details;
            this.message = message;
        }
        
        public Data() {
            this(null, null, null);
        }

        public Optional<String> code() {
            return Optional.ofNullable(this.code);
        }

        public Optional<Map<String, Object>> details() {
            return Optional.ofNullable(this.details);
        }

        public Optional<String> message() {
            return Optional.ofNullable(this.message);
        }

        public static Builder builder() {
            return new Builder();
        }


        public Data withCode(@Nullable String code) {
            this.code = code;
            return this;
        }


        public Data withDetails(@Nullable Map<String, Object> details) {
            this.details = details;
            return this;
        }


        public Data withMessage(@Nullable String message) {
            this.message = message;
            return this;
        }


        @Override
        public boolean equals(java.lang.Object o) {
            if (this == o) {
                return true;
            }
            if (o == null || getClass() != o.getClass()) {
                return false;
            }
            Data other = (Data) o;
            return 
                Utils.enhancedDeepEquals(this.code, other.code) &&
                Utils.enhancedDeepEquals(this.details, other.details) &&
                Utils.enhancedDeepEquals(this.message, other.message);
        }
        
        @Override
        public int hashCode() {
            return Utils.enhancedHash(
                code, details, message);
        }
        
        @Override
        public String toString() {
            return Utils.toString(Data.class,
                    "code", code,
                    "details", details,
                    "message", message);
        }

        @SuppressWarnings("UnusedReturnValue")
        public final static class Builder {

            private String code;

            private Map<String, Object> details;

            private String message;

            private Builder() {
              // force use of static builder() method
            }

            public Builder code(@Nullable String code) {
                this.code = code;
                return this;
            }

            public Builder details(@Nullable Map<String, Object> details) {
                this.details = details;
                return this;
            }

            public Builder message(@Nullable String message) {
                this.message = message;
                return this;
            }

            public Data build() {
                return new Data(
                    code, details, message);
            }

        }
    }

}

