/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.webhooks;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import to.unified.unified_java_sdk.models.shared.DrinkInput;
import to.unified.unified_java_sdk.models.shared.Ingredient;
import to.unified.unified_java_sdk.utils.Utils;


public class StockUpdateRequestBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("drink")
    private DrinkInput drink;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ingredient")
    private Ingredient ingredient;

    @JsonCreator
    public StockUpdateRequestBody(
            @JsonProperty("drink") @Nullable DrinkInput drink,
            @JsonProperty("ingredient") @Nullable Ingredient ingredient) {
        this.drink = drink;
        this.ingredient = ingredient;
    }
    
    public StockUpdateRequestBody() {
        this(null, null);
    }

    public Optional<DrinkInput> drink() {
        return Optional.ofNullable(this.drink);
    }

    public Optional<Ingredient> ingredient() {
        return Optional.ofNullable(this.ingredient);
    }

    public static Builder builder() {
        return new Builder();
    }


    public StockUpdateRequestBody withDrink(@Nullable DrinkInput drink) {
        this.drink = drink;
        return this;
    }


    public StockUpdateRequestBody withIngredient(@Nullable Ingredient ingredient) {
        this.ingredient = ingredient;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StockUpdateRequestBody other = (StockUpdateRequestBody) o;
        return 
            Utils.enhancedDeepEquals(this.drink, other.drink) &&
            Utils.enhancedDeepEquals(this.ingredient, other.ingredient);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            drink, ingredient);
    }
    
    @Override
    public String toString() {
        return Utils.toString(StockUpdateRequestBody.class,
                "drink", drink,
                "ingredient", ingredient);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private DrinkInput drink;

        private Ingredient ingredient;

        private Builder() {
          // force use of static builder() method
        }

        public Builder drink(@Nullable DrinkInput drink) {
            this.drink = drink;
            return this;
        }

        public Builder ingredient(@Nullable Ingredient ingredient) {
            this.ingredient = ingredient;
            return this;
        }

        public StockUpdateRequestBody build() {
            return new StockUpdateRequestBody(
                drink, ingredient);
        }

    }
}
