workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    debug:
        inputs:
            - location: .speakeasy/openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-team/speakeasy-team/debug
targets:
    java-target:
        target: java
        source: debug
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/speakeasy-team/speakeasy-team/debug-java-code-samples
            labelOverride:
                fixedValue: Java (SDK)
            blocking: false
