/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.callbacks;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import to.unified.unified_java_sdk.models.shared.OrderInput;
import to.unified.unified_java_sdk.utils.Utils;


public class CreateOrderOrderUpdateRequestBody {
    /**
     * An order for a drink or ingredient.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order")
    private OrderInput order;

    @JsonCreator
    public CreateOrderOrderUpdateRequestBody(
            @JsonProperty("order") @Nullable OrderInput order) {
        this.order = order;
    }
    
    public CreateOrderOrderUpdateRequestBody() {
        this(null);
    }

    /**
     * An order for a drink or ingredient.
     */
    public Optional<OrderInput> order() {
        return Optional.ofNullable(this.order);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * An order for a drink or ingredient.
     */
    public CreateOrderOrderUpdateRequestBody withOrder(@Nullable OrderInput order) {
        this.order = order;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateOrderOrderUpdateRequestBody other = (CreateOrderOrderUpdateRequestBody) o;
        return 
            Utils.enhancedDeepEquals(this.order, other.order);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            order);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateOrderOrderUpdateRequestBody.class,
                "order", order);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private OrderInput order;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * An order for a drink or ingredient.
         */
        public Builder order(@Nullable OrderInput order) {
            this.order = order;
            return this;
        }

        public CreateOrderOrderUpdateRequestBody build() {
            return new CreateOrderOrderUpdateRequestBody(
                order);
        }

    }
}
