/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import to.unified.unified_java_sdk.utils.Utils;


public class DrinkInput {
    /**
     * The name of the drink.
     */
    @JsonProperty("name")
    private String name;

    /**
     * The price of one unit of the drink in US cents.
     */
    @JsonProperty("price")
    private double price;

    /**
     * The product code of the drink, only available when authenticated.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("productCode")
    private String productCode;

    /**
     * The type of drink.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private DrinkType type;

    /**
     * The volume of the drink in milliliters.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("volume")
    private Long volume;

    @JsonCreator
    public DrinkInput(
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("price") double price,
            @JsonProperty("productCode") @Nullable String productCode,
            @JsonProperty("type") @Nullable DrinkType type,
            @JsonProperty("volume") @Nullable Long volume) {
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.price = price;
        this.productCode = productCode;
        this.type = type;
        this.volume = volume;
    }
    
    public DrinkInput(
            @Nonnull String name,
            double price) {
        this(name, price, null,
            null, null);
    }

    /**
     * The name of the drink.
     */
    public String name() {
        return this.name;
    }

    /**
     * The price of one unit of the drink in US cents.
     */
    public double price() {
        return this.price;
    }

    /**
     * The product code of the drink, only available when authenticated.
     */
    public Optional<String> productCode() {
        return Optional.ofNullable(this.productCode);
    }

    /**
     * The type of drink.
     */
    public Optional<DrinkType> type() {
        return Optional.ofNullable(this.type);
    }

    /**
     * The volume of the drink in milliliters.
     */
    public Optional<Long> volume() {
        return Optional.ofNullable(this.volume);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The name of the drink.
     */
    public DrinkInput withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    /**
     * The price of one unit of the drink in US cents.
     */
    public DrinkInput withPrice(double price) {
        this.price = price;
        return this;
    }


    /**
     * The product code of the drink, only available when authenticated.
     */
    public DrinkInput withProductCode(@Nullable String productCode) {
        this.productCode = productCode;
        return this;
    }


    /**
     * The type of drink.
     */
    public DrinkInput withType(@Nullable DrinkType type) {
        this.type = type;
        return this;
    }


    /**
     * The volume of the drink in milliliters.
     */
    public DrinkInput withVolume(@Nullable Long volume) {
        this.volume = volume;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DrinkInput other = (DrinkInput) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.price, other.price) &&
            Utils.enhancedDeepEquals(this.productCode, other.productCode) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.volume, other.volume);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, price, productCode,
            type, volume);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DrinkInput.class,
                "name", name,
                "price", price,
                "productCode", productCode,
                "type", type,
                "volume", volume);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private double price;

        private String productCode;

        private DrinkType type;

        private Long volume;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The name of the drink.
         */
        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        /**
         * The price of one unit of the drink in US cents.
         */
        public Builder price(double price) {
            this.price = price;
            return this;
        }

        /**
         * The product code of the drink, only available when authenticated.
         */
        public Builder productCode(@Nullable String productCode) {
            this.productCode = productCode;
            return this;
        }

        /**
         * The type of drink.
         */
        public Builder type(@Nullable DrinkType type) {
            this.type = type;
            return this;
        }

        /**
         * The volume of the drink in milliliters.
         */
        public Builder volume(@Nullable Long volume) {
            this.volume = volume;
            return this;
        }

        public DrinkInput build() {
            return new DrinkInput(
                name, price, productCode,
                type, volume);
        }

    }
}
