/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * DrinkType
 * 
 * <p>The type of drink.
 */
public enum DrinkType {
    COCKTAIL("cocktail"),
    NON_ALCOHOLIC("non-alcoholic"),
    BEER("beer"),
    WINE("wine"),
    SPIRIT("spirit"),
    OTHER("other");

    @JsonValue
    private final String value;

    DrinkType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<DrinkType> fromValue(String value) {
        for (DrinkType o: DrinkType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

