/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import to.unified.unified_java_sdk.utils.Utils;

/**
 * Error
 * 
 * <p>An unknown error occurred interacting with the API.
 */
public class Error {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("code")
    private String code;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    private String message;

    @JsonCreator
    public Error(
            @JsonProperty("code") @Nullable String code,
            @JsonProperty("message") @Nullable String message) {
        this.code = code;
        this.message = message;
    }
    
    public Error() {
        this(null, null);
    }

    public Optional<String> code() {
        return Optional.ofNullable(this.code);
    }

    public Optional<String> message() {
        return Optional.ofNullable(this.message);
    }

    public static Builder builder() {
        return new Builder();
    }


    public Error withCode(@Nullable String code) {
        this.code = code;
        return this;
    }


    public Error withMessage(@Nullable String message) {
        this.message = message;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Error other = (Error) o;
        return 
            Utils.enhancedDeepEquals(this.code, other.code) &&
            Utils.enhancedDeepEquals(this.message, other.message);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            code, message);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Error.class,
                "code", code,
                "message", message);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String code;

        private String message;

        private Builder() {
          // force use of static builder() method
        }

        public Builder code(@Nullable String code) {
            this.code = code;
            return this;
        }

        public Builder message(@Nullable String message) {
            this.message = message;
            return this;
        }

        public Error build() {
            return new Error(
                code, message);
        }

    }
}
