/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * IngredientType
 * 
 * <p>The type of ingredient.
 */
public enum IngredientType {
    FRESH("fresh"),
    LONG_LIFE("long-life"),
    PACKAGED("packaged");

    @JsonValue
    private final String value;

    IngredientType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<IngredientType> fromValue(String value) {
        for (IngredientType o: IngredientType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

