/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import to.unified.unified_java_sdk.utils.Utils;


public class Ingredient {
    /**
     * The name of the ingredient.
     */
    @JsonProperty("name")
    private String name;

    /**
     * The product code of the ingredient, only available when authenticated.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("productCode")
    private String productCode;

    /**
     * The type of ingredient.
     */
    @JsonProperty("type")
    private IngredientType type;

    @JsonCreator
    public Ingredient(
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("productCode") @Nullable String productCode,
            @JsonProperty("type") @Nonnull IngredientType type) {
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.productCode = productCode;
        this.type = Optional.ofNullable(type)
            .orElseThrow(() -> new IllegalArgumentException("type cannot be null"));
    }
    
    public Ingredient(
            @Nonnull String name,
            @Nonnull IngredientType type) {
        this(name, null, type);
    }

    /**
     * The name of the ingredient.
     */
    public String name() {
        return this.name;
    }

    /**
     * The product code of the ingredient, only available when authenticated.
     */
    public Optional<String> productCode() {
        return Optional.ofNullable(this.productCode);
    }

    /**
     * The type of ingredient.
     */
    public IngredientType type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The name of the ingredient.
     */
    public Ingredient withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    /**
     * The product code of the ingredient, only available when authenticated.
     */
    public Ingredient withProductCode(@Nullable String productCode) {
        this.productCode = productCode;
        return this;
    }


    /**
     * The type of ingredient.
     */
    public Ingredient withType(@Nonnull IngredientType type) {
        this.type = Utils.checkNotNull(type, "type");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Ingredient other = (Ingredient) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.productCode, other.productCode) &&
            Utils.enhancedDeepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, productCode, type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Ingredient.class,
                "name", name,
                "productCode", productCode,
                "type", type);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private String productCode;

        private IngredientType type;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The name of the ingredient.
         */
        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        /**
         * The product code of the ingredient, only available when authenticated.
         */
        public Builder productCode(@Nullable String productCode) {
            this.productCode = productCode;
            return this;
        }

        /**
         * The type of ingredient.
         */
        public Builder type(@Nonnull IngredientType type) {
            this.type = Utils.checkNotNull(type, "type");
            return this;
        }

        public Ingredient build() {
            return new Ingredient(
                name, productCode, type);
        }

    }
}
