/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import to.unified.unified_java_sdk.utils.Utils;

/**
 * OrderInput
 * 
 * <p>An order for a drink or ingredient.
 */
public class OrderInput {
    /**
     * The product code of the drink or ingredient.
     */
    @JsonProperty("productCode")
    private String productCode;

    /**
     * The number of units of the drink or ingredient to order.
     */
    @JsonProperty("quantity")
    private long quantity;

    /**
     * The type of order.
     */
    @JsonProperty("type")
    private OrderType type;

    @JsonCreator
    public OrderInput(
            @JsonProperty("productCode") @Nonnull String productCode,
            @JsonProperty("quantity") long quantity,
            @JsonProperty("type") @Nonnull OrderType type) {
        this.productCode = Optional.ofNullable(productCode)
            .orElseThrow(() -> new IllegalArgumentException("productCode cannot be null"));
        this.quantity = quantity;
        this.type = Optional.ofNullable(type)
            .orElseThrow(() -> new IllegalArgumentException("type cannot be null"));
    }

    /**
     * The product code of the drink or ingredient.
     */
    public String productCode() {
        return this.productCode;
    }

    /**
     * The number of units of the drink or ingredient to order.
     */
    public long quantity() {
        return this.quantity;
    }

    /**
     * The type of order.
     */
    public OrderType type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The product code of the drink or ingredient.
     */
    public OrderInput withProductCode(@Nonnull String productCode) {
        this.productCode = Utils.checkNotNull(productCode, "productCode");
        return this;
    }


    /**
     * The number of units of the drink or ingredient to order.
     */
    public OrderInput withQuantity(long quantity) {
        this.quantity = quantity;
        return this;
    }


    /**
     * The type of order.
     */
    public OrderInput withType(@Nonnull OrderType type) {
        this.type = Utils.checkNotNull(type, "type");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrderInput other = (OrderInput) o;
        return 
            Utils.enhancedDeepEquals(this.productCode, other.productCode) &&
            Utils.enhancedDeepEquals(this.quantity, other.quantity) &&
            Utils.enhancedDeepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            productCode, quantity, type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(OrderInput.class,
                "productCode", productCode,
                "quantity", quantity,
                "type", type);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String productCode;

        private long quantity;

        private OrderType type;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The product code of the drink or ingredient.
         */
        public Builder productCode(@Nonnull String productCode) {
            this.productCode = Utils.checkNotNull(productCode, "productCode");
            return this;
        }

        /**
         * The number of units of the drink or ingredient to order.
         */
        public Builder quantity(long quantity) {
            this.quantity = quantity;
            return this;
        }

        /**
         * The type of order.
         */
        public Builder type(@Nonnull OrderType type) {
            this.type = Utils.checkNotNull(type, "type");
            return this;
        }

        public OrderInput build() {
            return new OrderInput(
                productCode, quantity, type);
        }

    }
}
