/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * OrderType
 * 
 * <p>The type of order.
 */
public enum OrderType {
    DRINK("drink"),
    INGREDIENT("ingredient");

    @JsonValue
    private final String value;

    OrderType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<OrderType> fromValue(String value) {
        for (OrderType o: OrderType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

