/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import to.unified.unified_java_sdk.utils.HasSecurity;
import to.unified.unified_java_sdk.utils.SpeakeasyMetadata;
import to.unified.unified_java_sdk.utils.Utils;


public class Security implements HasSecurity {

    @SpeakeasyMetadata("security:scheme=true,type=apiKey,subtype=header,name=Authorization")
    private String apiKey;


    @SpeakeasyMetadata("security:scheme=true,type=oauth2,name=Authorization")
    private String clientCredentials;

    @JsonCreator
    public Security(
            @Nullable String apiKey,
            @Nullable String clientCredentials) {
        this.apiKey = apiKey;
        this.clientCredentials = clientCredentials;
    }
    
    public Security() {
        this(null, null);
    }

    public Optional<String> apiKey() {
        return Optional.ofNullable(this.apiKey);
    }

    public Optional<String> clientCredentials() {
        return Optional.ofNullable(this.clientCredentials);
    }

    public static Builder builder() {
        return new Builder();
    }


    public Security withApiKey(@Nullable String apiKey) {
        this.apiKey = apiKey;
        return this;
    }


    public Security withClientCredentials(@Nullable String clientCredentials) {
        this.clientCredentials = clientCredentials;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Security other = (Security) o;
        return 
            Utils.enhancedDeepEquals(this.apiKey, other.apiKey) &&
            Utils.enhancedDeepEquals(this.clientCredentials, other.clientCredentials);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            apiKey, clientCredentials);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Security.class,
                "apiKey", apiKey,
                "clientCredentials", clientCredentials);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String apiKey;

        private String clientCredentials;

        private Builder() {
          // force use of static builder() method
        }

        public Builder apiKey(@Nullable String apiKey) {
            this.apiKey = apiKey;
            return this;
        }

        public Builder clientCredentials(@Nullable String clientCredentials) {
            this.clientCredentials = clientCredentials;
            return this;
        }

        public Security build() {
            return new Security(
                apiKey, clientCredentials);
        }

    }
}
