/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import to.unified.unified_java_sdk.SDKConfiguration;
import to.unified.unified_java_sdk.operations.Authenticate;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Options;
import to.unified.unified_java_sdk.utils.RetryConfig;
import to.unified.unified_java_sdk.utils.Utils;

public class AuthenticateRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private AuthenticateRequestBody request;
    private final Options.Builder optionsBuilder;

    public AuthenticateRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.optionsBuilder = Options.builder();
    }

    public AuthenticateRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    public AuthenticateRequestBuilder request(@Nonnull AuthenticateRequestBody request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private AuthenticateRequestBody _buildRequest() {
        return this.request;
    }
    
    public AuthenticateRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public AuthenticateResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<AuthenticateRequestBody, AuthenticateResponse> operation
              = new Authenticate.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
