/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Override;
import java.lang.String;
import java.net.http.HttpResponse;
import java.util.Optional;
import to.unified.unified_java_sdk.models.shared.Error;
import to.unified.unified_java_sdk.utils.Response;
import to.unified.unified_java_sdk.utils.Utils;


public class AuthenticateResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * An unknown error occurred interacting with the API.
     */
    private Error error;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * The api key to use for authenticated endpoints.
     */
    private AuthenticateResponseBody object;

    @JsonCreator
    public AuthenticateResponse(
            @Nonnull String contentType,
            @Nullable Error error,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse,
            @Nullable AuthenticateResponseBody object) {
        this.contentType = Optional.ofNullable(contentType)
            .orElseThrow(() -> new IllegalArgumentException("contentType cannot be null"));
        this.error = error;
        this.statusCode = statusCode;
        this.rawResponse = Optional.ofNullable(rawResponse)
            .orElseThrow(() -> new IllegalArgumentException("rawResponse cannot be null"));
        this.object = object;
    }
    
    public AuthenticateResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse) {
        this(contentType, null, statusCode,
            rawResponse, null);
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * An unknown error occurred interacting with the API.
     */
    public Optional<Error> error() {
        return Optional.ofNullable(this.error);
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return this.statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<InputStream> rawResponse() {
        return this.rawResponse;
    }

    /**
     * The api key to use for authenticated endpoints.
     */
    public Optional<AuthenticateResponseBody> object() {
        return Optional.ofNullable(this.object);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public AuthenticateResponse withContentType(@Nonnull String contentType) {
        this.contentType = Utils.checkNotNull(contentType, "contentType");
        return this;
    }


    /**
     * An unknown error occurred interacting with the API.
     */
    public AuthenticateResponse withError(@Nullable Error error) {
        this.error = error;
        return this;
    }


    /**
     * HTTP response status code for this operation
     */
    public AuthenticateResponse withStatusCode(int statusCode) {
        this.statusCode = statusCode;
        return this;
    }


    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public AuthenticateResponse withRawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
        this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
        return this;
    }


    /**
     * The api key to use for authenticated endpoints.
     */
    public AuthenticateResponse withObject(@Nullable AuthenticateResponseBody object) {
        this.object = object;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthenticateResponse other = (AuthenticateResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.error, other.error) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.object, other.object);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, error, statusCode,
            rawResponse, object);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AuthenticateResponse.class,
                "contentType", contentType,
                "error", error,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "object", object);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Error error;

        private int statusCode;

        private HttpResponse<InputStream> rawResponse;

        private AuthenticateResponseBody object;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(@Nonnull String contentType) {
            this.contentType = Utils.checkNotNull(contentType, "contentType");
            return this;
        }

        /**
         * An unknown error occurred interacting with the API.
         */
        public Builder error(@Nullable Error error) {
            this.error = error;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
            this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
            return this;
        }

        /**
         * The api key to use for authenticated endpoints.
         */
        public Builder object(@Nullable AuthenticateResponseBody object) {
            this.object = object;
            return this;
        }

        public AuthenticateResponse build() {
            return new AuthenticateResponse(
                contentType, error, statusCode,
                rawResponse, object);
        }

    }
}
