/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import to.unified.unified_java_sdk.utils.Utils;

/**
 * AuthenticateResponseBody
 * 
 * <p>The api key to use for authenticated endpoints.
 */
public class AuthenticateResponseBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("token")
    private String token;

    @JsonCreator
    public AuthenticateResponseBody(
            @JsonProperty("token") @Nullable String token) {
        this.token = token;
    }
    
    public AuthenticateResponseBody() {
        this(null);
    }

    public Optional<String> token() {
        return Optional.ofNullable(this.token);
    }

    public static Builder builder() {
        return new Builder();
    }


    public AuthenticateResponseBody withToken(@Nullable String token) {
        this.token = token;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthenticateResponseBody other = (AuthenticateResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.token, other.token);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            token);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AuthenticateResponseBody.class,
                "token", token);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String token;

        private Builder() {
          // force use of static builder() method
        }

        public Builder token(@Nullable String token) {
            this.token = token;
            return this;
        }

        public AuthenticateResponseBody build() {
            return new AuthenticateResponseBody(
                token);
        }

    }
}
