/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import to.unified.unified_java_sdk.utils.Utils;


public class AuthenticateRequestBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("password")
    private String password;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("username")
    private String username;

    @JsonCreator
    public AuthenticateRequestBody(
            @JsonProperty("password") @Nullable String password,
            @JsonProperty("username") @Nullable String username) {
        this.password = password;
        this.username = username;
    }
    
    public AuthenticateRequestBody() {
        this(null, null);
    }

    public Optional<String> password() {
        return Optional.ofNullable(this.password);
    }

    public Optional<String> username() {
        return Optional.ofNullable(this.username);
    }

    public static Builder builder() {
        return new Builder();
    }


    public AuthenticateRequestBody withPassword(@Nullable String password) {
        this.password = password;
        return this;
    }


    public AuthenticateRequestBody withUsername(@Nullable String username) {
        this.username = username;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthenticateRequestBody other = (AuthenticateRequestBody) o;
        return 
            Utils.enhancedDeepEquals(this.password, other.password) &&
            Utils.enhancedDeepEquals(this.username, other.username);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            password, username);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AuthenticateRequestBody.class,
                "password", password,
                "username", username);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String password;

        private String username;

        private Builder() {
          // force use of static builder() method
        }

        public Builder password(@Nullable String password) {
            this.password = password;
            return this;
        }

        public Builder username(@Nullable String username) {
            this.username = username;
            return this;
        }

        public AuthenticateRequestBody build() {
            return new AuthenticateRequestBody(
                password, username);
        }

    }
}
