/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import to.unified.unified_java_sdk.models.shared.OrderInput;
import to.unified.unified_java_sdk.utils.SpeakeasyMetadata;
import to.unified.unified_java_sdk.utils.Utils;


public class CreateOrderRequest {

    @SpeakeasyMetadata("request:mediaType=application/json")
    private List<OrderInput> requestBody;

    /**
     * The url to call when the order is updated.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=callback_url")
    private String callbackUrl;

    @JsonCreator
    public CreateOrderRequest(
            @Nonnull List<OrderInput> requestBody,
            @Nullable String callbackUrl) {
        this.requestBody = Optional.ofNullable(requestBody)
            .orElseThrow(() -> new IllegalArgumentException("requestBody cannot be null"));
        this.callbackUrl = callbackUrl;
    }
    
    public CreateOrderRequest(
            @Nonnull List<OrderInput> requestBody) {
        this(requestBody, null);
    }

    public List<OrderInput> requestBody() {
        return this.requestBody;
    }

    /**
     * The url to call when the order is updated.
     */
    public Optional<String> callbackUrl() {
        return Optional.ofNullable(this.callbackUrl);
    }

    public static Builder builder() {
        return new Builder();
    }


    public CreateOrderRequest withRequestBody(@Nonnull List<OrderInput> requestBody) {
        this.requestBody = Utils.checkNotNull(requestBody, "requestBody");
        return this;
    }


    /**
     * The url to call when the order is updated.
     */
    public CreateOrderRequest withCallbackUrl(@Nullable String callbackUrl) {
        this.callbackUrl = callbackUrl;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateOrderRequest other = (CreateOrderRequest) o;
        return 
            Utils.enhancedDeepEquals(this.requestBody, other.requestBody) &&
            Utils.enhancedDeepEquals(this.callbackUrl, other.callbackUrl);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            requestBody, callbackUrl);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateOrderRequest.class,
                "requestBody", requestBody,
                "callbackUrl", callbackUrl);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<OrderInput> requestBody;

        private String callbackUrl;

        private Builder() {
          // force use of static builder() method
        }

        public Builder requestBody(@Nonnull List<OrderInput> requestBody) {
            this.requestBody = Utils.checkNotNull(requestBody, "requestBody");
            return this;
        }

        /**
         * The url to call when the order is updated.
         */
        public Builder callbackUrl(@Nullable String callbackUrl) {
            this.callbackUrl = callbackUrl;
            return this;
        }

        public CreateOrderRequest build() {
            return new CreateOrderRequest(
                requestBody, callbackUrl);
        }

    }
}
