/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import to.unified.unified_java_sdk.utils.Utils;


public class Data {

    @JsonProperty("resultArray")
    private List<Long> resultArray;

    @JsonCreator
    public Data(
            @JsonProperty("resultArray") @Nonnull List<Long> resultArray) {
        this.resultArray = Optional.ofNullable(resultArray)
            .orElseThrow(() -> new IllegalArgumentException("resultArray cannot be null"));
    }

    public List<Long> resultArray() {
        return this.resultArray;
    }

    public static Builder builder() {
        return new Builder();
    }


    public Data withResultArray(@Nonnull List<Long> resultArray) {
        this.resultArray = Utils.checkNotNull(resultArray, "resultArray");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Data other = (Data) o;
        return 
            Utils.enhancedDeepEquals(this.resultArray, other.resultArray);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            resultArray);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Data.class,
                "resultArray", resultArray);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<Long> resultArray;

        private Builder() {
          // force use of static builder() method
        }

        public Builder resultArray(@Nonnull List<Long> resultArray) {
            this.resultArray = Utils.checkNotNull(resultArray, "resultArray");
            return this;
        }

        public Data build() {
            return new Data(
                resultArray);
        }

    }
}
