/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import to.unified.unified_java_sdk.utils.Utils;

/**
 * GetFoodResponseBody
 * 
 * <p>A food item.
 */
public class GetFoodResponseBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private String name;

    @JsonCreator
    public GetFoodResponseBody(
            @JsonProperty("name") @Nullable String name) {
        this.name = name;
    }
    
    public GetFoodResponseBody() {
        this(null);
    }

    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    public static Builder builder() {
        return new Builder();
    }


    public GetFoodResponseBody withName(@Nullable String name) {
        this.name = name;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetFoodResponseBody other = (GetFoodResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetFoodResponseBody.class,
                "name", name);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String name;

        private Builder() {
          // force use of static builder() method
        }

        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        public GetFoodResponseBody build() {
            return new GetFoodResponseBody(
                name);
        }

    }
}
