/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import static to.unified.unified_java_sdk.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import to.unified.unified_java_sdk.SDKConfiguration;
import to.unified.unified_java_sdk.operations.ListIngredients;
import to.unified.unified_java_sdk.utils.Headers;
import to.unified.unified_java_sdk.utils.Options;
import to.unified.unified_java_sdk.utils.RetryConfig;
import to.unified.unified_java_sdk.utils.Utils;

public class ListIngredientsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private ListIngredientsRequest request;
    private final Options.Builder optionsBuilder;

    public ListIngredientsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.optionsBuilder = Options.builder();
    }

    public ListIngredientsRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    public ListIngredientsRequestBuilder request(@Nonnull ListIngredientsRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private ListIngredientsRequest _buildRequest() {
        return this.request;
    }
    
    public ListIngredientsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public ListIngredientsResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<ListIngredientsRequest, ListIngredientsResponse> operation
              = new ListIngredients.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
