/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import to.unified.unified_java_sdk.models.shared.DrinkType;
import to.unified.unified_java_sdk.utils.SpeakeasyMetadata;
import to.unified.unified_java_sdk.utils.Utils;


public class ListDrinksRequest {
    /**
     * The type of drink to filter by. If not provided all drinks will be returned.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=drinkType")
    private DrinkType drinkType;

    @JsonCreator
    public ListDrinksRequest(
            @Nullable DrinkType drinkType) {
        this.drinkType = drinkType;
    }
    
    public ListDrinksRequest() {
        this(null);
    }

    /**
     * The type of drink to filter by. If not provided all drinks will be returned.
     */
    public Optional<DrinkType> drinkType() {
        return Optional.ofNullable(this.drinkType);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The type of drink to filter by. If not provided all drinks will be returned.
     */
    public ListDrinksRequest withDrinkType(@Nullable DrinkType drinkType) {
        this.drinkType = drinkType;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListDrinksRequest other = (ListDrinksRequest) o;
        return 
            Utils.enhancedDeepEquals(this.drinkType, other.drinkType);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            drinkType);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListDrinksRequest.class,
                "drinkType", drinkType);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private DrinkType drinkType;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The type of drink to filter by. If not provided all drinks will be returned.
         */
        public Builder drinkType(@Nullable DrinkType drinkType) {
            this.drinkType = drinkType;
            return this;
        }

        public ListDrinksRequest build() {
            return new ListDrinksRequest(
                drinkType);
        }

    }
}
