/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import to.unified.unified_java_sdk.utils.SpeakeasyMetadata;
import to.unified.unified_java_sdk.utils.Utils;


public class ListIngredientsRequest {
    /**
     * A list of ingredients to filter by. If not provided all ingredients will be returned.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=false,name=ingredients")
    private List<String> ingredients;


    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page")
    private long page;

    @JsonCreator
    public ListIngredientsRequest(
            @Nullable List<String> ingredients,
            long page) {
        this.ingredients = ingredients;
        this.page = page;
    }
    
    public ListIngredientsRequest(
            long page) {
        this(null, page);
    }

    /**
     * A list of ingredients to filter by. If not provided all ingredients will be returned.
     */
    public Optional<List<String>> ingredients() {
        return Optional.ofNullable(this.ingredients);
    }

    public long page() {
        return this.page;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A list of ingredients to filter by. If not provided all ingredients will be returned.
     */
    public ListIngredientsRequest withIngredients(@Nullable List<String> ingredients) {
        this.ingredients = ingredients;
        return this;
    }


    public ListIngredientsRequest withPage(long page) {
        this.page = page;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListIngredientsRequest other = (ListIngredientsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.ingredients, other.ingredients) &&
            Utils.enhancedDeepEquals(this.page, other.page);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            ingredients, page);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListIngredientsRequest.class,
                "ingredients", ingredients,
                "page", page);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<String> ingredients;

        private long page;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * A list of ingredients to filter by. If not provided all ingredients will be returned.
         */
        public Builder ingredients(@Nullable List<String> ingredients) {
            this.ingredients = ingredients;
            return this;
        }

        public Builder page(long page) {
            this.page = page;
            return this;
        }

        public ListIngredientsRequest build() {
            return new ListIngredientsRequest(
                ingredients, page);
        }

    }
}
