/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import to.unified.unified_java_sdk.utils.Utils;

/**
 * ListIngredientsResponseBody
 * 
 * <p>A list of ingredients.
 */
public class ListIngredientsResponseBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    private Data data;

    @JsonCreator
    public ListIngredientsResponseBody(
            @JsonProperty("data") @Nullable Data data) {
        this.data = data;
    }
    
    public ListIngredientsResponseBody() {
        this(null);
    }

    public Optional<Data> data() {
        return Optional.ofNullable(this.data);
    }

    public static Builder builder() {
        return new Builder();
    }


    public ListIngredientsResponseBody withData(@Nullable Data data) {
        this.data = data;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListIngredientsResponseBody other = (ListIngredientsResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.data, other.data);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            data);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListIngredientsResponseBody.class,
                "data", data);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Data data;

        private Builder() {
          // force use of static builder() method
        }

        public Builder data(@Nullable Data data) {
            this.data = data;
            return this;
        }

        public ListIngredientsResponseBody build() {
            return new ListIngredientsResponseBody(
                data);
        }

    }
}
