/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Override;
import java.lang.String;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Optional;
import to.unified.unified_java_sdk.models.shared.Drink;
import to.unified.unified_java_sdk.models.shared.Error;
import to.unified.unified_java_sdk.utils.Response;
import to.unified.unified_java_sdk.utils.Utils;


public class ListDrinksResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * A list of drinks.
     */
    private List<Drink> drinks;

    /**
     * An unknown error occurred interacting with the API.
     */
    private Error error;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    @JsonCreator
    public ListDrinksResponse(
            @Nonnull String contentType,
            @Nullable List<Drink> drinks,
            @Nullable Error error,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse) {
        this.contentType = Optional.ofNullable(contentType)
            .orElseThrow(() -> new IllegalArgumentException("contentType cannot be null"));
        this.drinks = drinks;
        this.error = error;
        this.statusCode = statusCode;
        this.rawResponse = Optional.ofNullable(rawResponse)
            .orElseThrow(() -> new IllegalArgumentException("rawResponse cannot be null"));
    }
    
    public ListDrinksResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse) {
        this(contentType, null, null,
            statusCode, rawResponse);
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * A list of drinks.
     */
    public Optional<List<Drink>> drinks() {
        return Optional.ofNullable(this.drinks);
    }

    /**
     * An unknown error occurred interacting with the API.
     */
    public Optional<Error> error() {
        return Optional.ofNullable(this.error);
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return this.statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<InputStream> rawResponse() {
        return this.rawResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public ListDrinksResponse withContentType(@Nonnull String contentType) {
        this.contentType = Utils.checkNotNull(contentType, "contentType");
        return this;
    }


    /**
     * A list of drinks.
     */
    public ListDrinksResponse withDrinks(@Nullable List<Drink> drinks) {
        this.drinks = drinks;
        return this;
    }


    /**
     * An unknown error occurred interacting with the API.
     */
    public ListDrinksResponse withError(@Nullable Error error) {
        this.error = error;
        return this;
    }


    /**
     * HTTP response status code for this operation
     */
    public ListDrinksResponse withStatusCode(int statusCode) {
        this.statusCode = statusCode;
        return this;
    }


    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ListDrinksResponse withRawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
        this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListDrinksResponse other = (ListDrinksResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.drinks, other.drinks) &&
            Utils.enhancedDeepEquals(this.error, other.error) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, drinks, error,
            statusCode, rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListDrinksResponse.class,
                "contentType", contentType,
                "drinks", drinks,
                "error", error,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private List<Drink> drinks;

        private Error error;

        private int statusCode;

        private HttpResponse<InputStream> rawResponse;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(@Nonnull String contentType) {
            this.contentType = Utils.checkNotNull(contentType, "contentType");
            return this;
        }

        /**
         * A list of drinks.
         */
        public Builder drinks(@Nullable List<Drink> drinks) {
            this.drinks = drinks;
            return this;
        }

        /**
         * An unknown error occurred interacting with the API.
         */
        public Builder error(@Nullable Error error) {
            this.error = error;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
            this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
            return this;
        }

        public ListDrinksResponse build() {
            return new ListDrinksResponse(
                contentType, drinks, error,
                statusCode, rawResponse);
        }

    }
}
