/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import to.unified.unified_java_sdk.utils.Utils;


public class RequestBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("url")
    private String url;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("webhook")
    private Webhook webhook;

    @JsonCreator
    public RequestBody(
            @JsonProperty("url") @Nullable String url,
            @JsonProperty("webhook") @Nullable Webhook webhook) {
        this.url = url;
        this.webhook = webhook;
    }
    
    public RequestBody() {
        this(null, null);
    }

    public Optional<String> url() {
        return Optional.ofNullable(this.url);
    }

    public Optional<Webhook> webhook() {
        return Optional.ofNullable(this.webhook);
    }

    public static Builder builder() {
        return new Builder();
    }


    public RequestBody withUrl(@Nullable String url) {
        this.url = url;
        return this;
    }


    public RequestBody withWebhook(@Nullable Webhook webhook) {
        this.webhook = webhook;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RequestBody other = (RequestBody) o;
        return 
            Utils.enhancedDeepEquals(this.url, other.url) &&
            Utils.enhancedDeepEquals(this.webhook, other.webhook);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            url, webhook);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RequestBody.class,
                "url", url,
                "webhook", webhook);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String url;

        private Webhook webhook;

        private Builder() {
          // force use of static builder() method
        }

        public Builder url(@Nullable String url) {
            this.url = url;
            return this;
        }

        public Builder webhook(@Nullable Webhook webhook) {
            this.webhook = webhook;
            return this;
        }

        public RequestBody build() {
            return new RequestBody(
                url, webhook);
        }

    }
}
