/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package to.unified.unified_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum Webhook {
    STOCK_UPDATE("stockUpdate");

    @JsonValue
    private final String value;

    Webhook(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<Webhook> fromValue(String value) {
        for (Webhook o: Webhook.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

